apiVersion: v1
kind: Service
metadata:
  name: examination
  labels:
    group: example
spec:
  selector:
    app: exam-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
    # - protocol: 'TCP'
    #   port: 443
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
  # labels:
  # app: second-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpression
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: anianima/ct665 #:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            initialDelaySeconds:
              5